version: 2
updates:
  # Keep npm dependencies up to date
  - package-ecosystem: "npm"
    directory: "/" # Location of the package.json file
    schedule:
      interval: "weekly" # Can be daily, weekly, or monthly
    # Optionally, you can set up a target branch, ignore specific dependencies, etc.
