name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cache:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20" # Specify your Node.js version

      - name: Cache Node.js modules
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

  lint:
    needs: cache
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20" # Specify your Node.js version

      - name: Install dependencies
        run: npm install

      - name: Run lint
        run: npm run lint

  test:
    needs: cache
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20" # Specify your Node.js version

      - name: Install dependencies
        run: npm install

      - name: TypeScript Type Checking
        run: npm run type-check

      - name: Run tests
        run: npm run test

      - name: Security Vulnerability Scanning
        run: npm audit --audit-level=high

      - name: Accessibility Checks
        run: npx pa11y-ci
